READY = "Готово"
CMD_SET_START_TEXT = "Введите текст для команды старт"
CMD_SET_CAPTION_TEXT = "Введите текст для подписи в результате"
CMD_MAILING = "Введите сообщение для рассылки"
AMOUNT_USERS = "Количество пользователей - {amount}"
MAILING_START = "Рассылка запущена"
MAILING_END = "Рассылка завершена"
